Đồ án cuối kì/ElectronicStore-master/ElectronicStore/Controllers/ElectronicStoreController.cs
using System;
using System.Collections.Generic;
using System.Data.Linq.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectronicStore.Models;
using PagedList;
namespace ElectronicStore.Controllers
{
    public class ElectronicStoreController : Controller
    {
        electronicDataContext data = new electronicDataContext();
        private List<SP> LaySP(int count)
        {
            return data.SPs.OrderByDescending(a => a.NgayCapNhat).Take(count).ToList();
        }
        // GET: ElectronicStore
        public ActionResult Index()
        {
            var spmoi = LaySP(7);
            return View(spmoi);
        }
        public ActionResult ThuongHieu()
        {
            var thuonghieu = from th in data.THUONGHIEUs select th;
            return PartialView(thuonghieu);
        }
        public ActionResult SpTheoThuongHieu(int id)
        {
            var sanpham = from sp in data.SPs where sp.MATH == id select sp ;
            return View(sanpham);
        }
        public ActionResult Details (int id)
        {
            var sanpham = from sp in data.SPs where sp.MaSP == id select sp;
            return View(sanpham.Single());
        }
        public ActionResult About()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Search(FormCollection f, int? page)
        {
            string chuoi = f["timkiem"].ToString();           
            int pageSize = 24;
            int pageNum = (page ?? 1);
            var lst = from s in data.SPs where s.TenSP.Contains(chuoi.Trim()) select s;
            return View(lst.ToPagedList(pageNum, pageSize));
        }
    }
}

Đồ án cuối kì/ElectronicStore-master/ElectronicStore/Controllers/UserController.cs
using ElectronicStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectronicStore.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        electronicDataContext db = new electronicDataContext();
        [HttpGet]
        public ActionResult Dangky()

        {
            return View();
        }
        [HttpPost]

        public ActionResult Dangky(FormCollection collection, KHACHHANG kh)
        {
            var hoten = collection["HotenKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var matkhaunhaplai = collection["Matkhaunhaplai"];
            var diachi = collection["Diachi"];
            var email = collection["Email"];
            var dienthoai = collection["DienThoai"];
            var ngaysinh = string.Format("{0:MM/dd/yyyy}", collection["Ngaysinh"]);
            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["loi1"] = "Không được bỏ trống họ tên ";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["loi2"] = "Không được trùng tên đăng nhập.";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["loi3"] = "Không được bỏ trống mật khẩu";
            }
            else if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["loi4"] = "Phải nhập lại mật khẩu trùng khớp";

            }
            if (String.IsNullOrEmpty(email))
            {
                ViewData["loi5"] = "Không được bỏ trống email";

            }
            if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["loi6"] = "Không được bỏ trống số điện thoại";
            }
            else
            {
                kh.HoTen = hoten;
                kh.TaiKhoan = tendn;
                kh.MatKhau = matkhau;               
                kh.Email = email;
                kh.DiaChiKH = diachi;
                kh.DienThoaiKH = dienthoai;
                kh.NgaySinh = DateTime.Parse(ngaysinh);
                db.KHACHHANGs.InsertOnSubmit(kh);
                db.SubmitChanges();
                return RedirectToAction("Dangnhap");

            }
            return Dangky();
        }
        public ActionResult Dangnhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {

            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["loi1"] = "Vui lòng nhập tên đăng nhập!";

            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["loi2"] = "Mật khẩu không được bỏ trống!";

            }
            else
            {

                KHACHHANG kh = db.KHACHHANGs.FirstOrDefault(n => n.TaiKhoan.CompareTo(tendn) == 0 && n.MatKhau.CompareTo(matkhau) == 0);
                if (kh != null)
                {
                    ViewBag.Thongbao = "Đăng nhập thành công!";
                    Session["Taikhoan"] = kh;

                }
                else
                    ViewBag.Thongbao = " Tên đăng nhập hoặc mật khẩu không đúng! ";
            }
            return RedirectToAction("GioHang","GioHang");

        }
        public PartialViewResult ID()
        {
            if (Session["Taikhoan"] != null)
            {
                KHACHHANG kh = (KHACHHANG) Session["Taikhoan"];
                ViewBag.ThongBao = kh.TaiKhoan;
            }
            return PartialView();
        }
    }
}

Đồ án cuối kì/ElectronicStore-master/ElectronicStore/Views/Shared/GioHangPartial.cshtml
@{
    var s = Session["GioHang"];
}
@if (s is List<ElectronicStore.Models.GioHang> cart)
{
    <a href="@Url.Action("GioHang", "GioHang")">
        <i class="fa fa-shopping-cart"></i>
        <span>Giỏ hàng mún ăn nữa</span>
        <div class="qty">@cart.Count</div>
    </a>
}
else
{
    <a href="@Url.Action("GioHang", "GioHang")">
        <i class="fa fa-shopping-cart"></i>
        <span>Giỏ hàng đang rỗng</span>
        <div class="qty">0</div>
    </a>
}

Đồ án cuối kì/ElectronicStore-master/ElectronicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Đồ án cuối kì/ElectronicStore-master/ElectronicStore/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>DẾ IU CỦA MẸ - Đồ án môn ASP</title>
    <link rel="icon" type="image/jpg" href="~/Images/icon.jpg" />
    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">

    <!-- Bootstrap -->
    <link type="text/css" rel="stylesheet" href="~/Content/bootstrap.min.css" />

    <!-- Slick -->
    <link type="text/css" rel="stylesheet" href="~/Content/slick.css" />
    <link type="text/css" rel="stylesheet" href="~/Content/slick-theme.css" />
    <!-- nouislider -->
    <link type="text/css" rel="stylesheet" href="~/Content/nouislider.min.css" />
    <!-- Font Awesome Icon -->
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">
    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="~/Content/style.css" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- import icon font awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>
    <!-- HEADER -->
    <header>
        <!-- TOP HEADER -->
        <div id="top-header">
            <div class="container">
                <ul class="header-links pull-left">
                    <li><a href="tel:0325893888"><i class="fa fa-phone"></i> (+84) 325 893 888</a></li>
                    <li><a href="mailto:vinhphuc931998@gmail.com"><i class="fa fa-envelope-o"></i> Gửi mail cho chúng tôi</a></li>
                    <li><a href="@Url.Action("About","ElectronicStore")"><i class="fa fa-map-marker"></i> 20 Phan Đăng Lưu, Phường 6, Phú Nhuận, Thành phố Hồ Chí Minh</a></li>
                </ul>
                <ul class="header-links pull-right">

                    <li><a href="#"><i class="fa fa-dollar"></i> VNĐ</a></li>
                    <li><a href="@Url.Action("Dangnhap","User")"><i class="fa fa-user-o"> </i> My Account</a></li>
                    <li><a>@Html.Action("ID", "User")</a></li>
                </ul>
            </div>
        </div>
        <!-- /TOP HEADER -->
        <!-- MAIN HEADER -->
        <div id="header">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <!-- LOGO -->
                    <div class="col-md-3">
                        <div class="header-logo">
                            <a href="@Url.Action("Index","ElectronicStore")" class="logo">
                                <img src="~/Images/logoweb.png" alt="">
                            </a>
                        </div>
                    </div>
                    <!-- /LOGO -->
                    @*@Html.Action("Search", "ElectronicStore")*@
                    <!-- SEARCH BAR -->
                    <div class="col-md-6">
                        <div class="header-search">
                            @using (Html.BeginForm("Search", "ElectronicStore", FormMethod.Post))
                            {
                                <form>
                                    <!--<select class="input-select">
                                        <option value="0">Sản phẩm</option>-->
                                        @*<option value="1">Category 01</option>
                                        <option value="1">Category 02</option>*@
                                    <!--</select>-->
                                    <input class="input" name="timkiem" id="timkiem" placeholder="Bạn cần sản phẩm nào nè :3">
                                    <input type="submit" class="search-btn" value="Search" />
                                </form>
                            }
                        </div>                    
                    </div>                   
                    <!-- /SEARCH BAR -->
                    <!-- ACCOUNT -->
                    <div class="col-md-3 clearfix">
                        <div class="header-ctn">
                            <!-- Wishlist -->
                            <!-- /Wishlist -->
                            <!-- Cart -->
                            <div>
                                @Html.Partial("GioHangPartial")
                            </div>
                            <!-- /Cart -->
                            <!-- Menu Toogle -->
                            <div class="menu-toggle">
                                <a href="#">
                                    <i class="fa fa-bars"></i>
                                    <span>Menu</span>
                                </a>
                            </div>
                            <!-- /Menu Toogle -->
                        </div>
                    </div>
                    <!-- /ACCOUNT -->
                </div>
                <!-- row -->
            </div>
            <!-- container -->
        </div>
        <!-- /MAIN HEADER -->
    </header>
    <!-- /HEADER -->
    <!-- NAVIGATION -->
    <nav id="navigation">
        <!-- container -->
        <div class="container">
            <!-- responsive-nav -->
            <div id="responsive-nav">
                <!-- NAV -->
                <ul class="main-nav nav navbar-nav">
                    <li class="active"><a href="@Url.Action("Index","ElectronicStore")">Home</a></li>
                    @Html.Action("ThuongHieu", "ElectronicStore")
                </ul>
                <!-- /NAV -->
            </div>
            <!-- /responsive-nav -->
        </div>
        <!-- /container -->
    </nav>
    <!-- /NAVIGATION -->
    <!-- SECTION -->
    <div>
        @RenderBody()
    </div>
    <!-- /SECTION -->
    <!-- HOT DEAL SECTION -->
    <!-- /HOT DEAL SECTION -->
    <!-- SECTION -->
    <!-- /SECTION -->
    <!-- SECTION -->
    <!-- /SECTION -->
    <!-- NEWSLETTER -->
    <div id="newsletter" class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">
                <div class="col-md-12">
                    <div class="newsletter">
                        <p>Gửi email bạn cho chúng tôi để được nhận <strong>thông tin mới nhất</strong></p>
                        <form>
                            <input class="input" type="email" placeholder="cho mình xin mail của bạn ik">
                            <button class="newsletter-btn"><i class="fa fa-envelope"></i> Gửi nè</button>
                        </form>
                        <ul class="newsletter-follow">
                            <li>
                                <a href="https://www.facebook.com/banlaptop.somee.vn"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /NEWSLETTER -->
    <!-- FOOTER -->
    <footer id="footer">
        <!-- top footer -->
        <div class="section">
            <!-- container -->
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Giới thiệu</h3>
                            <p>Laptop cho sinh viên, smartphone cho mẹ iu :3</p>
                            <ul class="footer-links">
                                <li><a href="@Url.Action("About","ElectronicStore")"><i class="fa fa-map-marker"></i>20 Phan Đăng Lưu, Phường 6, Phú Nhuận, Thành phố Hồ Chí Minh</a></li>
                                <li><a href="tel:0325893888"><i class="fa fa-phone"></i>(+84) 325 893 888</a></li>
                                <li><a href="mailto:vinhphuc931998@gmail.com"><i class="fa fa-envelope-o"></i>vinhphuc931998@gmail.com</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Categories</h3>
                            <ul class="footer-links">
                                <li><a href="#">Giá sốc</a></li>
                                <li><a href="#">Laptops</a></li>
                                <li><a href="#">Smartphones</a></li>
                                <li><a href="#">Cameras</a></li>
                                <li><a href="#">Phụ kiện</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="clearfix visible-xs"></div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Thông tin</h3>
                            <ul class="footer-links">
                                <li><a href="@Url.Action("About","ElectronicStore")">Giới thiệu</a></li>
                                <li><a href="#">Liện hệ</a></li>
                                <li><a href="#">Privacy Policy</a></li>
                                <li><a href="#">Orders and Returns</a></li>
                                <li><a href="#">Terms & Conditions</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3 col-xs-6">
                        <div class="footer">
                            <h3 class="footer-title">Service</h3>
                            <ul class="footer-links">
                                <li><a href="#">My Account</a></li>
                                <li><a href="#">Xem giỏ hàng</a></li>
                                <li><a href="#">Danh sách muốn mua</a></li>
                                <li><a href="#">Theo dõi đơn hàng</a></li>
                                <li><a href="#">Help</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /top footer -->
        <!-- bottom footer -->
        <div id="bottom-footer" class="section">
            <div class="container">
                <!-- row -->
                <div class="row">
                    <div class="col-md-12 text-center">
                        <ul class="footer-payments">
                            <li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
                            <li><a href="#"><i class="fa fa-credit-card"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
                            <li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </div>
        <!-- /bottom footer -->
    </footer>
    <!-- /FOOTER -->
    <!-- jQuery Plugins -->
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/slick.min.js"></script>
    <script src="~/Scripts/nouislider.min.js"></script>
    <script src="~/Scripts/jquery.zoom.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    <!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                xfbml: true,
                version: 'v3.2'
            });
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>

    <!-- Your customer chat code -->
    <div class="fb-customerchat"
         attribution=setup_tool
         page_id="408210473303497">
    </div>
</body>
</html>